### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by shuntas** [shuntas/protospace-123456#1]
# URL
https://protospace-123456.herokuapp.com/

# Basic認証
ユーザーID：------
パスワード：------

**Comment by EigoNakashima-tech** [comment]
山田さん、ご提出ありがとうございます！

挙動確認させていただいたところ、以下の不備が見受けられましたので、修正をお願いいたします！



- 編集画面にアクセスするとエラーが出てしまう

- トップページにユーザー名が表示されていない



修正次第、フォーム提出を再度お願いいたします！
